spring.application.name=respondly

# OpenAI API Configuration
#spring.ai.openai.api-key={OPENAI_API_KEY}

# Google Gemini Configuration
gemini.api.key=${GOOGLE_API_KEY}
gemini.api.url=${GOOGLE_API_URL}
#test.val=HelloWorld testing value annotation injection

#GOOGLE_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
#spring.ai.gemini.api.url=https://generativelanguage.googleapis.com
#GOOGLE_API_KEY=AIzaSyDvP33MKX8-KK3LiYA_hVS51zDm8Z05Vzo;
