spring.application.name=respondly
spring.application.version=v1.0.0
text.application.version=1.0.0

# ================ STARTUP BANNER ================#
#https://rwinch.github.io/spring-boot/features/spring-application/banner.html
# spring.output.ansi.enabled=ALWAYS
# spring.banner.location=classpath:/path/to/banner/bannername.txt

#================ LLM  CONFIGURATION ================#
# OpenAI API Configuration
#spring.ai.openai.api-key={OPENAI_API_KEY}

# Google Gemini Configuration
gemini.api.url=${GOOGLE_API_URL}
gemini.api.key=${GOOGLE_API_KEY}
#test.val=HelloWorld testing value annotation injection

#================ LOGGING CONFIGURATION ================#
# Enable colorful console output for Spring Boot applications within IntelliJ IDEA
spring.output.ansi.enabled=ALWAYS
